import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { 
  Share2, 
  Copy, 
  Check, 
  Mail, 
  MessageSquare, 
  Linkedin, 
  Twitter,
  Link2,
  FileText,
  Download
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  description: string;
  metrics?: {
    co2Reduction?: number;
    costSavings?: number;
    efficiencyGain?: number;
  };
  type: 'recommendation' | 'sustainability' | 'simulation';
}

export default function ShareModal({ 
  isOpen, 
  onClose, 
  title, 
  description,
  metrics,
  type 
}: ShareModalProps) {
  const [copied, setCopied] = useState(false);
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');

  const shareUrl = `${window.location.origin}/dashboard?shared=true`;
  
  const shareText = metrics 
    ? `🌍 ${title}\n\n${description}\n\n📊 Key Metrics:\n• CO₂ Reduction: -${metrics.co2Reduction}%\n• Cost Savings: -${metrics.costSavings}%\n• Efficiency Gain: +${metrics.efficiencyGain}%\n\nGenerated by NEXUS-AI`
    : `🌍 ${title}\n\n${description}\n\nGenerated by NEXUS-AI`;

  const handleCopyLink = async () => {
    await navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    toast({
      title: "Link copied! 🔗",
      description: "Share link has been copied to clipboard.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyText = async () => {
    await navigator.clipboard.writeText(shareText);
    toast({
      title: "Content copied! 📋",
      description: "Share content has been copied to clipboard.",
    });
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(`NEXUS-AI: ${title}`);
    const body = encodeURIComponent(shareText + `\n\nView more: ${shareUrl}`);
    window.open(`mailto:${email}?subject=${subject}&body=${body}`);
    toast({
      title: "Email client opened! 📧",
      description: "Compose your email to share this insight.",
    });
  };

  const handleSocialShare = (platform: 'twitter' | 'linkedin') => {
    const encodedText = encodeURIComponent(shareText);
    const encodedUrl = encodeURIComponent(shareUrl);
    
    const urls = {
      twitter: `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedUrl}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`
    };
    
    window.open(urls[platform], '_blank', 'width=600,height=400');
    toast({
      title: `Opening ${platform}... 🚀`,
      description: "Share window has been opened.",
    });
  };

  const handleDownloadReport = () => {
    const reportContent = `
NEXUS-AI Report
===============

${title}
${'='.repeat(title.length)}

${description}

${metrics ? `
Key Metrics
-----------
• CO₂ Reduction: -${metrics.co2Reduction}%
• Cost Savings: -${metrics.costSavings}%
• Efficiency Gain: +${metrics.efficiencyGain}%
` : ''}

Generated on: ${new Date().toLocaleString()}
Powered by NEXUS-AI - UAE Water-Energy Nexus Optimization
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `nexus-ai-${type}-report.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast({
      title: "Report downloaded! 📄",
      description: "Your report has been saved.",
    });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Share2 className="h-5 w-5 text-primary" />
            Share {type === 'recommendation' ? 'Recommendation' : type === 'sustainability' ? 'Impact Report' : 'Simulation'}
          </DialogTitle>
          <DialogDescription>
            Share this insight with your team or stakeholders
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 pt-2">
          {/* Preview */}
          <div className="p-3 rounded-lg bg-muted/50 border border-border">
            <h4 className="font-medium text-sm text-foreground mb-1">{title}</h4>
            <p className="text-xs text-muted-foreground line-clamp-2">{description}</p>
            {metrics && (
              <div className="flex gap-2 mt-2">
                <Badge variant="secondary" className="text-xs">
                  CO₂: -{metrics.co2Reduction}%
                </Badge>
                <Badge variant="secondary" className="text-xs">
                  Cost: -{metrics.costSavings}%
                </Badge>
              </div>
            )}
          </div>

          {/* Copy Link */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Share Link</label>
            <div className="flex gap-2">
              <Input 
                value={shareUrl} 
                readOnly 
                className="text-sm"
              />
              <Button variant="outline" size="icon" onClick={handleCopyLink}>
                {copied ? <Check className="h-4 w-4 text-success" /> : <Copy className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          <Separator />

          {/* Social Share */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Share on Social</label>
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                className="flex-1"
                onClick={() => handleSocialShare('twitter')}
              >
                <Twitter className="h-4 w-4 mr-2" />
                Twitter
              </Button>
              <Button 
                variant="outline" 
                className="flex-1"
                onClick={() => handleSocialShare('linkedin')}
              >
                <Linkedin className="h-4 w-4 mr-2" />
                LinkedIn
              </Button>
            </div>
          </div>

          <Separator />

          {/* Email Share */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Share via Email</label>
            <div className="flex gap-2">
              <Input 
                type="email"
                placeholder="recipient@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="text-sm"
              />
              <Button 
                variant="outline" 
                onClick={handleEmailShare}
                disabled={!email}
              >
                <Mail className="h-4 w-4" />
              </Button>
            </div>
          </div>

          <Separator />

          {/* Actions */}
          <div className="flex gap-2">
            <Button variant="outline" className="flex-1" onClick={handleCopyText}>
              <FileText className="h-4 w-4 mr-2" />
              Copy Text
            </Button>
            <Button variant="outline" className="flex-1" onClick={handleDownloadReport}>
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
